### ISSUE TITLE
Roadmap : A list of prioritised issues.

### ISSUE THREAD

**Issue by piyush-garg** [fabric8io/kubernetes-client#1018]
A list of prioritised for FKC. These issues are part of the [backlog](https://github.com/fabric8io/kubernetes-client/projects/1) and we are prioritising in our following sprints:

## Feature
- [x] Implement waiUntilCondition #989 
- [ ] Kubernetes/Openshift mock server should be able to take customized config for client #998 
- [ ] Provide equivalent of `oc new-app` #929 
- [ ] Template does not support ${{ }} #959 
- [x] Create ISTIO Route Rule #942 
- [ ] Add support for service catalog #973

## Kubernetes and OpenShift Compatibility
- [x] API version support for openshift #919 
- [x] Kubernetes/Openshift version compatibility #946
- [x] [upgrade] Support for Kubernetes/Openshift v1.9/v3.9 #1020  

## Test
- [x] Add support for log() and exec() #975 

## Documentation
- [x] Add contributor guidelines #980 
- [x] Add a doc that lists projects using the client #935 

## Uncategorised (Bug Fixes )
- [x] Kubernetes Connection is not closed #1013 
- [x] waitUntilReady does not work for big timeouts #917 
- [x] Not able to trigger build via WebhookTriggerbuild #986 
- [x] Failure in update while on CRUD mode #957 
- [ ] Add Location Header while deleting a project #1006 
- [x] Multiple document handling breaks #1004 
- [x] Loading a template is breaking #1005 
- [ ] Close is not closing the connection immediately #960 
- [ ] Unable to update stateful set if spec contains an empty array #931 
- [ ] Fluent Object does not contain Additional Properties mao #993 
- [x] Use exec, copy file to pod is too slow #1008 
- [x] DSL execute too slow #1008 
- [x] Create Cron Job #920 

This list is just a first stab at handling and reducing the backlog that we have accumulated in the fabric8-kubernetes-client issues list. Please comment on this issue and let us know if you feel there are issues that we might have overlooked or need to be prioritized.

**Comment by MaitreDede** [comment]
Hi,
I would be pleased to have cronjobs api avaible :)

**Comment by brentpearson** [comment]
+1 for cronjobs!

**Comment by skonto** [comment]
Could you also add (unless it already exists) a method to wait on some result/condition from a command executed against a pod (required it here https://github.com/apache/spark/pull/21652#discussion_r200135218).
Timeouts like here: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecPipesExample.java#L60
look a bit arbitrary.

**Comment by rohanKanojia** [comment]
@skonto Do you think #989 matches your usecase? It's in our plan for implementation

**Comment by skonto** [comment]
@rohanKanojia I will have a look, using a terminal with a container is my use case.
