### ISSUE TITLE
[EPIC] Release Fabric8 Kubernetes Client 6.0.0 (RC + GA)

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4190]
### Tasks
- [x] Review milestone
- [x] Release 6.0.0-RC1
  https://github.com/fabric8io/kubernetes-client/releases/tag/v6.0.0-RC1
- [x] Blog post about Release Candidate
  https://blog.marcnuri.com/fabric8-kubernetes-client-6-0-0-rc1
- [x] Quarkus draft PR
  https://github.com/quarkusio/quarkus/pull/26107
- [x] Eclipse JKube draft PR
  https://github.com/eclipse/jkube/pull/1464
- [x] Eclipse JKube IT repo Uses RC1
  https://github.com/jkubeio/jkube-integration-tests/pull/174
- [x] Bump JKube integration tests dependency
  https://github.com/jkubeio/jkube-integration-tests/pull/174
- [x] Release 6.0.0
  https://github.com/fabric8io/kubernetes-client/releases/tag/v6.0.0
- [x] Quarkus modifications https://github.com/quarkusio/quarkus/pull/26107
- [x] Blog post about GA
  https://blog.marcnuri.com/fabric8-kubernetes-client-6-0-0
- [x] Blog post about GA es_ES
  https://blog.marcnuri.com/fabric8-kubernetes-client-6-0-0-es
- [x] Blog post about GA in Red Hat Developer @shawkins 
  https://developers.redhat.com/articles/2022/07/15/new-http-clients-java-generator-and-more-fabric8-600
- [x] Blog post about the CRD to Java generator @sunix
- [x] Blog post about the usage of the JDK Client
  https://blog.marcnuri.com/kubernetes-client-6-httpclient-how-to
- [x] Blog post about the usage of the Jetty Client
  https://blog.marcnuri.com/kubernetes-client-6-httpclient-how-to
- [x] Blog post about the usage of the Vert.x Client
  https://blog.marcnuri.com/kubernetes-client-6-httpclient-how-to
- ~Blog post about visit resources~
