### ISSUE TITLE
Release Fabric8 Kubernetes Client 5.12.3

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4297]
### Tasks
- [x] Verify 5.12 branch is up to date (has the v5.12.2 tag as latest)
- [x] Merge PRs targeting this branch
  - https://github.com/fabric8io/kubernetes-client/pull/4229
  - https://github.com/fabric8io/kubernetes-client/pull/4276
  - https://github.com/fabric8io/kubernetes-client/pull/4282
- [x] Backport any outstanding issue
  - https://github.com/fabric8io/kubernetes-client/pull/4050
  - https://github.com/fabric8io/kubernetes-client/pull/4295
- [x] Test 5.12 branch 
- [x] Release
  - https://github.com/fabric8io/kubernetes-client/actions/runs/2746726995
  - https://github.com/fabric8io/kubernetes-client/releases/tag/v5.12.3
- [x] Merge 5.12 into master
- [x] Bump Quarkus version
  - https://github.com/quarkusio/quarkus/pull/26969

**Comment by wangyang0918** [comment]
Big +1 for this patch release. Apache Flink will bump the fabric8 kubernetes-client version after the release.

**Comment by manusa** [comment]
We'll try to release this week or the next.

> Apache Flink will bump the fabric8 kubernetes-client version after the release.

What are your plans regarding v 6.0?

**Comment by wangyang0918** [comment]
It seems that a lot of dependencies have changed in the v6.0. And the leader elector is also refactored. I am afraid we might need more testing on this major release. I hope it could be done in Flink 1.17 or 1.18(the release 1.16 is on the way).
