### ISSUE TITLE
Release Fabric8 Kubernetes Client 5.12.4

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4454]
### Description

Issue to track the required tasks to release Fabric8 Kubernetes Client 5.12.4.

- https://github.com/fabric8io/kubernetes-client/milestone/49

### Tasks
- [x] Verify 5.12 branch is up to date (has the v5.12.3 tag as latest)
- [x] Backport any [outstanding issue](https://github.com/fabric8io/kubernetes-client/labels/5.12.x)
  - [x] https://github.com/fabric8io/kubernetes-client/pull/4263
  - [x] https://github.com/fabric8io/kubernetes-client/pull/4264
  - [x] https://github.com/fabric8io/kubernetes-client/pull/4381
  - [x] https://github.com/fabric8io/kubernetes-client/pull/4461
- [x] Merge PRs targeting this branch
  - https://github.com/fabric8io/kubernetes-client/pull/4412
  - https://github.com/fabric8io/kubernetes-client/pull/4424
  - https://github.com/fabric8io/kubernetes-client/pull/4455
  - https://github.com/fabric8io/kubernetes-client/pull/4457
  - https://github.com/fabric8io/kubernetes-client/pull/4458
  - https://github.com/fabric8io/kubernetes-client/pull/4463
- [x] Test 5.12 branch 
- [x] Release
  - https://github.com/fabric8io/kubernetes-client/releases/tag/v5.12.4
- [x] Merge 5.12 into master
- [x] Bump Quarkus dependency version (2.13)
  - https://github.com/quarkusio/quarkus/pull/28321
