### ISSUE TITLE
Move fabric8io/mockwebserver to this repository

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5430]
### Description

Move the [MockWebServer](https://github.com/fabric8io/mockwebserver) to this repository.

### Tasks

- [x] Merge or close pending PRs
  - https://github.com/fabric8io/mockwebserver/pull/56
  - https://github.com/fabric8io/mockwebserver/pull/74
  - https://github.com/fabric8io/mockwebserver/pull/78
  - https://github.com/fabric8io/mockwebserver/pull/79
- [x] Move module to https://github.com/fabric8io/kubernetes-client repo
  #5465
- [x] Publish move notice
  https://github.com/fabric8io/mockwebserver/pull/80
- [x] Archive repository 
- [x] Deal with zjsonpatch
  - #3489
  - #4700
  - Created https://github.com/fabric8io/kubernetes-client/issues/5480 for specific tracking
- [x] Refactors
  - Keep Spock tests?
    Doesn't seem necessary for now.
  - https://github.com/fabric8io/kubernetes-client/pull/5481

### Relates to
- #4113
- #5307
