### ISSUE TITLE
Set Java baseline to 11

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#6081]
## Description

Part of #5778 

Starting from version 7.0.0, the Fabric8 Kubernetes Client will require at minimum Java 11 to work.

## Tasks
- [x] Bump Maven Compiler source and target versions
  https://github.com/fabric8io/kubernetes-client/blob/50497aac5be2b3550a9cca10e5ace5eaccdb59f4/pom.xml#L174-L175
- [x] Remove Maven compiler settings overrides
  https://github.com/fabric8io/kubernetes-client/blob/8622505401460c0189059e4b7d8824db87d7837c/junit/kube-api-test/pom.xml#L37-L41
  https://github.com/fabric8io/kubernetes-client/blob/8622505401460c0189059e4b7d8824db87d7837c/httpclient-jdk/pom.xml#L32
  https://github.com/fabric8io/kubernetes-client/blob/8622505401460c0189059e4b7d8824db87d7837c/httpclient-jetty/pom.xml#L32
  https://github.com/fabric8io/kubernetes-client/blob/8622505401460c0189059e4b7d8824db87d7837c/httpclient-tests/pom.xml#L32
- [x] Remove Java-11 specific profile in Maven pom.xml files and merge with defaults
  https://github.com/fabric8io/kubernetes-client/blob/50497aac5be2b3550a9cca10e5ace5eaccdb59f4/pom.xml#L1509
  Pay attention to what was done in #5190
- [x] Remove 8 from build pipeline
  https://github.com/fabric8io/kubernetes-client/blob/3c889e7752fa2b841c8764a62c1754df0bdf963f/.github/workflows/build.yml#L47
- [x] Change to 11 in e2e-tests pipeline
  https://github.com/fabric8io/kubernetes-client/blob/e3fa9c82a2c5a5ebdbca41334a2181a5b4df1253/.github/workflows/e2e-tests.yml#L55-L58
  https://github.com/fabric8io/kubernetes-client/blob/e3fa9c82a2c5a5ebdbca41334a2181a5b4df1253/.github/workflows/e2e-tests.yml#L90
  https://github.com/fabric8io/kubernetes-client/blob/e3fa9c82a2c5a5ebdbca41334a2181a5b4df1253/.github/workflows/e2e-tests.yml#L121
  https://github.com/fabric8io/kubernetes-client/blob/e3fa9c82a2c5a5ebdbca41334a2181a5b4df1253/.github/workflows/e2e-tests.yml#L152
- [x] Change to 11 in javadocs pipeline
  https://github.com/fabric8io/kubernetes-client/blob/2540a22cbbb804950cdb9130db42bed9754787d8/.github/workflows/javadocs.yml#L47-L50
- [x] Simplify release and release-snapshots pipelines
  Everything can now be released in a single pass
  Pay attention to what was done in #5190
- [x] Add entry in [migration guide](https://github.com/fabric8io/kubernetes-client/blob/7074fbc338cdb832449395f5221649906d1b06da/doc/MIGRATION-v7.md)

**Comment by andreaTP** [comment]
Now that we are at it:
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

Java 11 is almost out of the support phase, would it make sense to bump directly to Java 17?

**Comment by manusa** [comment]
> Now that we are at it: https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> 
> Java 11 is almost out of the support phase, would it make sense to bump directly to Java 17?

Refer to https://github.com/fabric8io/kubernetes-client/issues/5778#issuecomment-2190468324

Most companies are going to provide commercial support for Java 11 well passed that date (just check the paid support column in your link).

The only reason I (personally) see to bump now is because it's becoming extremely difficult to maintain the project with such a low baseline, many of our dependencies have moved to Java 11.
Other than that, there are no clear advantages of upgrading the baseline past 11 and on the other hand there many disadvantages to do so.

**Comment by jorsol** [comment]
> > Now that we are at it: https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> > Java 11 is almost out of the support phase, would it make sense to bump directly to Java 17?
> 
> Refer to [#5778 (comment)](https://github.com/fabric8io/kubernetes-client/issues/5778#issuecomment-2190468324)
> 
> Most companies are going to provide commercial support for Java 11 well passed that date (just check the paid support column in your link).

This project should not be tied to companies that provide commercial support for Java 11... see my comment for a longer explanation: https://github.com/fabric8io/kubernetes-client/issues/5778#issuecomment-2191416898

But most importantly, if you check current ecosystem reports like the [New Relic](https://newrelic.com/resources/report/2024-state-of-the-java-ecosystem) one, new Java versions are being adopted faster, is possible that Java 17 is more used than Java 11 right now... Spring 6 (Boot 3) and Quarkus 3.7 require Java 17 as the baseline, in other words, the ecosystem is starting to move faster.

> The only reason I (personally) see to bump now is because it's becoming extremely difficult to maintain the project with such a low baseline, many of our dependencies have moved to Java 11. Other than that, there are no clear advantages of upgrading the baseline past 11 and on the other hand there many disadvantages to do so.

This is just my personal opinion, but I think there are more advantages of upgrading past 11 than disadvantages. There will be always trade-offs, so if you feel comfortable with Java 11 that's a good baseline too.

**Comment by manusa** [comment]
> there are more advantages of upgrading past 11

Such as? (I'm referring specifically for this code-base and those advantages that would be impactful from a user's perspective)

**Comment by jorsol** [comment]
> > there are more advantages of upgrading past 11
> 
> Such as? (I'm referring specifically for this code-base and those advantages that would be impactful from a user's perspective)

Impactful from a user's perspective probably no, but advantages for the code-base maintainability could be, with Java 17 you have switch expression, text blocks, records, sealed classes, etc... all that would require some refactoring and the effort could not be worth it, but at least for new code or parts that can be refactored, there is an opportunity for that.

In any case, I don't mind keeping Java 11 as the baseline, I'm not a maintainer or even a casual contributor, and this discussion (that probably already happened) should be done with the team that maintains the project, so again, is just my personal preference, don't take it as advice or recommendation 😉 .

**Comment by manusa** [comment]
:) no worries

> Impactful from a user's perspective probably no

I was just making sure that there wasn't anything else that could actually be interesting for users and that we missed out when weighing the pros/cons.


Personally, I need to keep multiple pet projects just to be able to test Java's new features :sweat_smile: Otherwise it's groundhog day in 2014 :sob:
